// Scopes the compiled Billing CSS under `.billing-scope` so it can live inside the main app
// without touching other pages. Usage: node scripts/billing-import/scope-css.mjs <billing.css> <out.css>
import fs from "node:fs";
import postcss from "postcss";

const [, , input, output] = process.argv;
const css = fs.readFileSync(input, "utf8");
const SCOPE = ".billing-scope";

const FONT_VARS = {
  "--font-sans": "--bfont-sans",
  "--font-heading": "--bfont-heading",
  "--font-body": "--bfont-body",
};

const root = postcss.parse(css);

// drop the Google Fonts @import (the app already loads Figtree + DM Sans through next/font)
root.walkAtRules("import", (r) => r.remove());

function scopeSelector(sel) {
  sel = sel.trim();
  if (/^(:root|:host|html|body)(\s*,.*)?$/.test(sel) || sel === ":root" || sel === ":host") return SCOPE;
  if (sel.startsWith("html.js ")) return `html.js ${SCOPE} ${sel.slice(8)}`;
  if (/^(:root|:host|html|body)\b/.test(sel)) return sel.replace(/^(:root|:host|html|body)/, SCOPE);
  if (sel === "*" || sel.startsWith("*") || sel.startsWith(":before") || sel.startsWith(":after") || sel.startsWith("::")) {
    return `${SCOPE} ${sel}, ${SCOPE}${sel.startsWith("*") ? sel.slice(1) : sel}`.replace(/,\s*\.billing-scope$/, "");
  }
  return `${SCOPE} ${sel}`;
}

root.walkRules((rule) => {
  // keyframe steps (from/to/50%) are not selectors
  if (rule.parent && rule.parent.type === "atrule" && /keyframes$/i.test(rule.parent.name)) return;
  const parts = [];
  // split on top-level commas
  let depth = 0, cur = "";
  for (const ch of rule.selector) {
    if (ch === "(" || ch === "[") depth++;
    if (ch === ")" || ch === "]") depth--;
    if (ch === "," && depth === 0) { parts.push(cur); cur = ""; } else cur += ch;
  }
  parts.push(cur);
  const out = [...new Set(parts.map(scopeSelector))];
  rule.selector = out.join(", ");
});

// the theme variables live on the scope element; point fonts at the app's next/font variables
root.walkDecls((d) => {
  for (const [from, to] of Object.entries(FONT_VARS)) {
    if (d.prop === from) d.prop = to;
    if (d.value.includes(`var(${from}`)) d.value = d.value.split(`var(${from}`).join(`var(${to}`);
  }
});
root.walkRules(SCOPE, (rule) => {
  if (rule.parent && rule.parent.type === "atrule" && rule.parent.name === "layer" && rule.parent.params === "theme") {
    rule.walkDecls("--bfont-sans", (d) => (d.value = "var(--font-sans)"));
    rule.walkDecls("--bfont-body", (d) => (d.value = "var(--font-sans)"));
    rule.walkDecls("--bfont-heading", (d) => (d.value = "var(--font-display)"));
    rule.walkDecls("--default-font-family", (d) => (d.value = "var(--font-sans)"));
  }
});

fs.writeFileSync(output, "/* Generated by scripts/billing-import/scope-css.mjs: do not edit by hand. */\n" + root.toString());
console.log("wrote", output);
