/* eslint-disable */
// Generated by scripts/billing-import/convert.mjs from the static Billing HTML. Edit the HTML source and re-run, or edit this file directly.
import { FeaturesHeroVisual } from "./FeaturesHeroVisual";
import { FeaturesSections } from "./FeaturesSections";

export function BillingFeaturesContent() {
  return (
    <>
      {/* ============ Billing sub-menu ============ */}
      <header className="z-40 transition-all duration-300 sticky top-0 border-b border-slate-200/80" style={{ backgroundColor: "#eef1ef" }} data-submenu="">
        <div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8">
          <div className="flex min-h-16 flex-col items-stretch gap-3 py-3 sm:flex-row sm:items-center sm:gap-4 sm:py-0">
            <a className="inline-flex min-w-0 flex-shrink-0 items-center gap-3 rounded-xl py-1 transition-opacity hover:opacity-80 sm:gap-6 sm:px-6" aria-label="Go to Billing home" href="/billing">
              <img src="/billing/images/billing-logo.png" alt="Billing" className="h-9 w-auto object-contain" />
            </a>
            <nav className="flex items-center gap-1 overflow-x-auto px-0 py-1.5 sm:px-1.5" aria-label="Billing navigation">
              <a className="inline-flex shrink-0 items-center rounded-full px-4 py-2 text-[0.95rem] font-semibold transition-colors shadow-sm" style={{ backgroundColor: "#00ab87", color: "#ffffff" }} href="/billing/features">
                Features
              </a>
              <a className="inline-flex shrink-0 items-center rounded-full px-4 py-2 text-[0.95rem] font-semibold transition-colors hover:bg-black/5" style={{ color: "#00ab87" }} href="/billing/pricing">
                Pricing
              </a>
            </nav>
          </div>
        </div>
      </header>
      {/* ============ Features hero ============ */}
      <section className="relative overflow-hidden pb-10 pt-16 lg:pb-14 lg:pt-20" style={{ background: "linear-gradient(180deg, #f8fcfa 0%, #eef6f3 100%)" }} data-reveal-group="" data-stagger="0.09" data-delay-children="0.05" data-duration="0.6" data-margin="-8%">
        <div aria-hidden="true" className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute -left-40 top-0 h-[480px] w-[480px] rounded-full" style={{ background: "radial-gradient(circle, rgba(212, 241, 230, 0.85) 0%, rgba(212, 241, 230, 0) 70%)" }}></div>
          <div className="absolute -right-32 top-24 h-[520px] w-[520px] rounded-full" style={{ background: "radial-gradient(circle, rgba(170, 224, 200, 0.5) 0%, rgba(170, 224, 200, 0) 70%)" }}></div>
        </div>
        <div className="relative mx-auto max-w-6xl px-5 text-center">
          <h1 className="mx-auto max-w-[17ch] sm:max-w-[26ch] text-[36px] font-semibold leading-[1.1] tracking-[-0.02em] sm:text-[46px] lg:max-w-none lg:text-[52px]" style={{ color: "var(--billing-depth, #0e342c)", "--reveal-y": "24px" } as React.CSSProperties} data-reveal="">
            Everything you need to manage
            <br className="hidden lg:block" />
            {" "}billing from one place.
          </h1>
          <p className="mx-auto mt-6 max-w-[78ch] text-[16.5px] leading-[1.7]" style={{ color: "rgba(14, 52, 44, 0.62)", "--reveal-y": "24px" } as React.CSSProperties} data-reveal="">
            Create invoices, set flexible billing rules, collect payments and stay on top of receivables. EVOQ Billing gives you the tools to manage what customers owe and what your business needs to collect.
          </p>
          <div className="mt-10 lg:mt-12" data-reveal="" style={{ "--reveal-y": "24px" } as React.CSSProperties}>
            <FeaturesHeroVisual />
          </div>
        </div>
      </section>
      <FeaturesSections />
      {/* ============ Ready to make billing easier? ============ */}
      <section className="relative overflow-hidden" style={{ background: "linear-gradient(180deg, #ffffff 0%, #eef6f3 100%)", padding: "72px 0 96px" }}>
        <div style={{ maxWidth: 1240, margin: "0 auto", padding: "0 20px" }}>
          <div style={{ position: "relative", overflow: "hidden", borderRadius: 44, padding: "72px 28px", textAlign: "center", background: "linear-gradient(135deg, #0b2b24 0%, #145646 55%, #00ab88 140%)", boxShadow: "0 60px 110px -50px rgba(0, 120, 95, 0.7)" }}>
            <div aria-hidden="true" style={{ position: "absolute", left: -90, top: -90, width: 320, height: 320, borderRadius: "50%", background: "radial-gradient(circle, rgba(111,227,192,.35), rgba(111,227,192,0) 70%)" }}></div>
            <div aria-hidden="true" style={{ position: "absolute", right: -80, bottom: -110, width: 380, height: 380, borderRadius: "50%", background: "radial-gradient(circle, rgba(251,232,129,.28), rgba(251,232,129,0) 70%)" }}></div>
            <svg aria-hidden="true" width="100%" height="100%" viewBox="0 0 1000 400" preserveAspectRatio="none" style={{ position: "absolute", inset: 0, opacity: 0.25 }} fill="none">
              <path d="M0 330 C 220 260, 340 380, 560 300 S 860 220, 1000 280" stroke="#6fe3c0" strokeWidth="1.5" strokeDasharray="5 8" vectorEffect="non-scaling-stroke" />
            </svg>
            <div style={{ position: "relative" }}>
              <div style={{ display: "inline-flex", gap: 10, marginBottom: 26 }}>
                {[["#d4f1e6", "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8l6 6v12a2 2 0 0 1-2 2z M14 2v6h6 M9 13h6 M9 17h4"], ["#fbe881", "M20 6 9 17l-5-5"], ["#e6e2fb", "M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9 M10.3 21a1.94 1.94 0 0 0 3.4 0"]].map(([bg, d]) => (
                  <span key={bg} style={{ width: 48, height: 48, borderRadius: 16, background: bg, color: "#0e342c", display: "inline-flex", alignItems: "center", justifyContent: "center", boxShadow: "0 16px 30px -14px rgba(0,0,0,.5)" }}>
                    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d={d} /></svg>
                  </span>
                ))}
              </div>
              <h2 style={{ margin: 0, color: "#fff", fontSize: 44, fontWeight: 600, lineHeight: 1.1, letterSpacing: "-0.02em" }}>Ready to make billing easier?</h2>
              <p style={{ margin: "20px auto 0", maxWidth: "56ch", fontSize: 17, lineHeight: 1.7, color: "rgba(255,255,255,.78)" }}>
                Bring your pricing, invoices, payments, and receivables together and spend less time managing the work behind every payment.
              </p>
              <div style={{ marginTop: 34, display: "flex", gap: 14, justifyContent: "center", flexWrap: "wrap" }}>
                <a href="#get-started" className="no-underline transition-all duration-200 hover:-translate-y-0.5" style={{ display: "inline-flex", alignItems: "center", gap: 10, background: "#fff", color: "#0e342c", fontSize: 15, fontWeight: 700, padding: "15px 30px", borderRadius: 99, textDecoration: "none", boxShadow: "0 18px 34px -16px rgba(0,0,0,.5)" }}>
                  Get Started
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12h14" /><path d="m12 5 7 7-7 7" /></svg>
                </a>
                <a href="/billing/pricing" className="no-underline transition-all duration-200 hover:-translate-y-0.5" style={{ display: "inline-flex", alignItems: "center", gap: 10, color: "#fff", fontSize: 15, fontWeight: 700, padding: "15px 30px", borderRadius: 99, textDecoration: "none", border: "1.5px solid rgba(255,255,255,.45)", background: "rgba(255,255,255,.08)" }}>
                  View Pricing
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* ============ Footer ============ */}
      {/* ============ Pop-up forms (front-end only) ============ */}
      <div data-modal="get-started" hidden>
        <div style={{ position: "fixed", inset: "0px", zIndex: "100", background: "rgba(20, 22, 32, 0.55)", backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center", padding: "20px" }} data-modal-overlay="">
          <div role="dialog" aria-modal="true" style={{ position: "relative", width: "100%", maxWidth: "560px", maxHeight: "90vh", overflowY: "auto", background: "rgb(255, 255, 255)", border: "1px solid transparent", borderRadius: "20px", boxShadow: "rgba(15, 18, 28, 0.45) 0px 40px 80px -20px", padding: "32px 36px 28px" }}>
            <button aria-label="Close" style={{ position: "absolute", top: "24px", right: "24px", width: "36px", height: "36px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(95, 107, 122)", fontSize: "16px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" }} data-modal-close="">
              ×
            </button>
            <div data-view="form">
              <div style={{ fontFamily: "var(--font-sans)", fontSize: "12px", fontWeight: "700", letterSpacing: "0.06em", textTransform: "uppercase", color: "rgb(71, 71, 224)", marginBottom: "6px" }}>
                EVOQ
              </div>
              <h2 style={{ fontFamily: "var(--font-display)", fontSize: "26px", fontWeight: "700", color: "rgb(31, 36, 48)", margin: "0px 0px 6px", letterSpacing: "-0.01em" }}>
                Get Started
              </h2>
              <p style={{ fontFamily: "var(--font-sans)", fontSize: "14.5px", color: "rgb(95, 107, 122)", margin: "0px" }}>
                Tell us about your business.
              </p>
              <div style={{ height: "1px", background: "rgb(237, 239, 243)", margin: "22px 0px" }}></div>
              <form>
                <div style={{ marginBottom: "20px" }}>
                  <label style={{ display: "block", fontFamily: "var(--font-sans)", fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.04em", textTransform: "uppercase", color: "rgb(95, 107, 122)", marginBottom: "8px" }}>
                    Name{" "}
                    <span style={{ color: "rgb(71, 71, 224)" }}>
                      *
                    </span>
                  </label>
                  <input required placeholder="Jane Smith" type="text" defaultValue="" name="name" style={{ width: "100%", padding: "12px 14px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", fontFamily: "var(--font-sans)", fontSize: "14px", color: "rgb(31, 36, 48)", background: "rgb(255, 255, 255)", outline: "none", boxSizing: "border-box" }} />
                </div>
                <div style={{ marginBottom: "20px" }}>
                  <label style={{ display: "block", fontFamily: "var(--font-sans)", fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.04em", textTransform: "uppercase", color: "rgb(95, 107, 122)", marginBottom: "8px" }}>
                    Company{" "}
                    <span style={{ color: "rgb(71, 71, 224)" }}>
                      *
                    </span>
                  </label>
                  <input required placeholder="Acme Corporation" type="text" defaultValue="" name="companyName" style={{ width: "100%", padding: "12px 14px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", fontFamily: "var(--font-sans)", fontSize: "14px", color: "rgb(31, 36, 48)", background: "rgb(255, 255, 255)", outline: "none", boxSizing: "border-box" }} />
                </div>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginBottom: "20px" }}>
                  <div>
                    <label style={{ display: "block", fontFamily: "var(--font-sans)", fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.04em", textTransform: "uppercase", color: "rgb(95, 107, 122)", marginBottom: "8px" }}>
                      Work Email{" "}
                      <span style={{ color: "rgb(71, 71, 224)" }}>
                        *
                      </span>
                    </label>
                    <input required placeholder="jane@company.com" type="email" defaultValue="" name="email" style={{ width: "100%", padding: "12px 14px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", fontFamily: "var(--font-sans)", fontSize: "14px", color: "rgb(31, 36, 48)", background: "rgb(255, 255, 255)", outline: "none", boxSizing: "border-box" }} />
                  </div>
                  <div>
                    <label style={{ display: "block", fontFamily: "var(--font-sans)", fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.04em", textTransform: "uppercase", color: "rgb(95, 107, 122)", marginBottom: "8px" }}>
                      Phone
                    </label>
                    <input placeholder="+1 (555) 000-0000" type="tel" defaultValue="" name="phone" style={{ width: "100%", padding: "12px 14px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", fontFamily: "var(--font-sans)", fontSize: "14px", color: "rgb(31, 36, 48)", background: "rgb(255, 255, 255)", outline: "none", boxSizing: "border-box" }} />
                  </div>
                </div>
                <div style={{ marginBottom: "20px" }}>
                  <label style={{ display: "block", fontFamily: "var(--font-sans)", fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.04em", textTransform: "uppercase", color: "rgb(95, 107, 122)", marginBottom: "8px" }}>
                    Team Size
                  </label>
                  <select name="teamSize" style={{ width: "100%", padding: "12px 14px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", fontFamily: "var(--font-sans)", fontSize: "14px", color: "rgb(31, 36, 48)", background: "rgb(255, 255, 255)", outline: "none", boxSizing: "border-box", cursor: "pointer" }} defaultValue="">
                    <option value="" disabled>
                      Select range
                    </option>
                    <option value="1-10">
                      1–10
                    </option>
                    <option value="11-50">
                      11–50
                    </option>
                    <option value="51-200">
                      51–200
                    </option>
                    <option value="201-500">
                      201–500
                    </option>
                    <option value="500+">
                      500+
                    </option>
                  </select>
                </div>
                <div style={{ marginBottom: "8px" }} data-picker="" data-accent="#4747E0" data-border="#E6EAF0">
                  <label style={{ display: "block", fontFamily: "var(--font-sans)", fontSize: "11.5px", fontWeight: "700", letterSpacing: "0.04em", textTransform: "uppercase", color: "rgb(95, 107, 122)", marginBottom: "8px" }}>
                    Products of Interest
                  </label>
                  <div style={{ position: "relative" }}>
                    <button type="button" style={{ width: "100%", padding: "12px 14px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", fontFamily: "var(--font-sans)", fontSize: "14px", color: "rgb(31, 36, 48)", background: "rgb(255, 255, 255)", outline: "none", boxSizing: "border-box", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", cursor: "pointer", textAlign: "left" }} data-picker-toggle="">
                      <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", color: "rgb(155, 168, 183)" }} data-picker-label="">
                        Select products
                      </span>
                      <span style={{ flexShrink: "0", transition: "transform 0.15s", transform: "rotate(0deg)", color: "rgb(155, 168, 183)", fontSize: "11px" }} data-caret="">
                        ▼
                      </span>
                    </button>
                    <div style={{ marginTop: "8px", background: "rgb(255, 255, 255)", border: "1px solid rgb(230, 234, 240)", borderRadius: "10px", padding: "14px 16px", maxHeight: "220px", overflowY: "auto" }} data-picker-list="" hidden>
                      <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          CRM
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Campaigns
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          ServiceOps
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Desk
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Projects
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Sync
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Inventory
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          HRMS
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Payroll
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          HRMS Plus
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Skillberry
                        </button>
                        <button type="button" aria-pressed="false" style={{ padding: "7px 14px", borderRadius: "999px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "13px", fontWeight: "600", cursor: "pointer", transition: "background 0.12s,\n                            border-color 0.12s,\n                            color 0.12s" }} data-chip="">
                          Others
                        </button>
                      </div>
                    </div>
                  </div>
                  <input type="text" data-picker-others="" hidden placeholder="Tell us what you're looking for" style={{ width: "100%", padding: "12px 14px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", fontFamily: "var(--font-sans)", fontSize: "14px", color: "rgb(31, 36, 48)", background: "rgb(255, 255, 255)", outline: "none", boxSizing: "border-box", marginTop: "10px" }} />
                </div>
                <div style={{ height: "1px", background: "rgb(237, 239, 243)", margin: "20px 0px 18px" }}></div>
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px" }}>
                  <span style={{ fontFamily: "var(--font-sans)", fontSize: "12.5px", color: "rgb(71, 71, 224)" }}>
                    * Required fields
                  </span>
                  <div style={{ display: "flex", gap: "10px" }}>
                    <button type="button" style={{ padding: "11px 20px", borderRadius: "10px", border: "1px solid rgb(230, 234, 240)", background: "rgb(255, 255, 255)", color: "rgb(31, 36, 48)", fontFamily: "var(--font-sans)", fontSize: "14px", fontWeight: "600", cursor: "pointer" }} data-modal-close="">
                      Cancel
                    </button>
                    <button type="submit" style={{ display: "inline-flex", alignItems: "center", gap: "8px", padding: "11px 22px", borderRadius: "10px", border: "0px", background: "rgb(71, 71, 224)", color: "rgb(255, 255, 255)", fontFamily: "var(--font-sans)", fontSize: "14px", fontWeight: "700", cursor: "pointer", opacity: "1", boxShadow: "rgba(71, 71, 224, 0.5) 0px 8px 24px -8px" }}>
                      Get Started
                    </button>
                  </div>
                </div>
              </form>
            </div>
            <div data-view="success" hidden>
              <div style={{ padding: "40px 8px 24px", textAlign: "center" }}>
                <div style={{ width: "56px", height: "56px", borderRadius: "50%", background: "rgb(71, 71, 224)", color: "rgb(255, 255, 255)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "26px", margin: "0px auto 20px" }}>
                  ✓
                </div>
                <h2 style={{ fontFamily: "var(--font-display)", fontSize: "22px", fontWeight: "700", color: "rgb(31, 36, 48)", margin: "0px 0px 8px" }}>
                  You're all set
                </h2>
                <p style={{ fontFamily: "var(--font-sans)", fontSize: "14.5px", color: "rgb(95, 107, 122)", margin: "0px" }}>
                  A member of our team will reach out shortly to schedule your walkthrough.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
